In [ ]:
#reading the files
#import pandas as pd

#df = pd.read_csv("/content/all_reviews(2018-2022).csv", encoding='latin1')

#df

### **Spelling has been corrected, so we continue with the preprocessing stepping but this is spelling code used**

# **Spelling Corrections**

In [ ]:
#!pip install textblob

In [ ]:
#from textblob import TextBlob

In [ ]:
# Function to perform spell correction on a string
#def correct_spelling(text):
    #blob = TextBlob(text)
    #return str(blob.correct())

In [ ]:
#df['Review'] = df['Review'].apply(correct_spelling)

In [ ]:
#df

In [ ]:
#df.to_csv('all review_correct_spellings(2018-2022).csv', index=True)

In [ ]:
## importing corrected spelling csv
import pandas as pd
df = pd.read_csv("/content/all review_correct_spellings(2018-2022).csv", encoding='latin1')

df

       Year     Data_Source                                             Review
0      2022  Airline Rating  I tried to fly out of GJT yesterday afternoon....
1      2022  Airline Rating  The rude woman at the front desk got mad at me...
2      2022  Airline Rating  Since weÂÂre back to our normal 50,000 miles...
3      2022  Airline Rating  U(. K American airline, literally ruined our t...
4      2022  Airline Rating  Horse airline ever\nOnÂÂt recommend anyone t...
...     ...             ...                                                ...
23294  2018      Trustpilot  it was fine the flight attendants were nice an...
23295  2018      Trustpilot  First time flying with American Airline on bus...
23296  2018      Trustpilot  There were too many instances of rude service ...
23297  2018      Trustpilot  Have a business class ticket and had access to...
23298  2018      Trustpilot  Terrible experience. By daughter's flight from...

[23299 rows x 3 columns]

#** Expansion of contractions**

In [ ]:
!pip install contractions

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.2-py3-none-any.whl (289 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 7.7 MB/s eta 0:00:00
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.0.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 kB 12.6 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.2 contractions-0.1.73 pyahocorasick-2.0.0 textsearch-0.0.24

In [ ]:
import contractions

In [ ]:
#Expansion of contractions
def expand_contractions(text):
    words = []
    for word in text.split():
            words.append(contractions.fix(word))
    return ' '.join(words)

#Apply the expand_contractions function to the 'Review' column of the DataFrame
df['Review'] = df['Review'].apply(expand_contractions)
df

       Year     Data_Source                                             Review
0      2022  Airline Rating  I tried to fly out of GJT yesterday afternoon....
1      2022  Airline Rating  The rude woman at the front desk got mad at me...
2      2022  Airline Rating  Since weÂÂre back to our normal 50,000 miles...
3      2022  Airline Rating  YOU(. K American airline, literally ruined our...
4      2022  Airline Rating  Horse airline ever OnÂÂt recommend anyone to...
...     ...             ...                                                ...
23294  2018      Trustpilot  it was fine the flight attendants were nice an...
23295  2018      Trustpilot  First time flying with American Airline on bus...
23296  2018      Trustpilot  There were too many instances of rude service ...
23297  2018      Trustpilot  Have a business class ticket and had access to...
23298  2018      Trustpilot  Terrible experience. By daughter's flight from...

[23299 rows x 3 columns]

# **common case**

In [ ]:
#common case
def text_lowercase(text):
    return text.lower()

# Apply the text_lowercase() function to the 'Review' column using the apply() method
df['Review'] = df['Review'].apply(text_lowercase)
df

       Year     Data_Source                                             Review
0      2022  Airline Rating  i tried to fly out of gjt yesterday afternoon....
1      2022  Airline Rating  the rude woman at the front desk got mad at me...
2      2022  Airline Rating  since weââre back to our normal 50,000 miles...
3      2022  Airline Rating  you(. k american airline, literally ruined our...
4      2022  Airline Rating  horse airline ever onâât recommend anyone to...
...     ...             ...                                                ...
23294  2018      Trustpilot  it was fine the flight attendants were nice an...
23295  2018      Trustpilot  first time flying with american airline on bus...
23296  2018      Trustpilot  there were too many instances of rude service ...
23297  2018      Trustpilot  have a business class ticket and had access to...
23298  2018      Trustpilot  terrible experience. by daughter's flight from...

[23299 rows x 3 columns]

# **Text Substitution**

so the marker like symbols can be removed in this stage bold text

In [ ]:
# Text Substitution  so the marker like symbols can be removed in this stage
import re
def remove_markers(text):
    pattern = r"(@[A-Za-z0-9_]+)|[^\w\s]|#|http\S+"
    text = re.sub(pattern, '', text)
    return text

# apply the remove_markers function to the 'my_column' column
df['Review'] = df['Review'].apply(remove_markers)
df

       Year     Data_Source                                             Review
0      2022  Airline Rating  i tried to fly out of gjt yesterday afternoon ...
1      2022  Airline Rating  the rude woman at the front desk got mad at me...
2      2022  Airline Rating  since weââre back to our normal 50000 miles or...
3      2022  Airline Rating  you k american airline literally ruined our tr...
4      2022  Airline Rating  horse airline ever onâât recommend anyone to t...
...     ...             ...                                                ...
23294  2018      Trustpilot  it was fine the flight attendants were nice an...
23295  2018      Trustpilot  first time flying with american airline on bus...
23296  2018      Trustpilot  there were too many instances of rude service ...
23297  2018      Trustpilot  have a business class ticket and had access to...
23298  2018      Trustpilot  terrible experience by daughters flight from r...

[23299 rows x 3 columns]

In [ ]:
# remove numbers
def remove_numbers(text):
  pattern = r'\d+'
  text = re.sub(pattern,"",text)
  return text

In [ ]:
# apply the function to the 'my_column' column
df['Review'] = df['Review'].apply(remove_numbers)
df

       Year     Data_Source                                             Review
0      2022  Airline Rating  i tried to fly out of gjt yesterday afternoon ...
1      2022  Airline Rating  the rude woman at the front desk got mad at me...
2      2022  Airline Rating  since weââre back to our normal  miles or so a...
3      2022  Airline Rating  you k american airline literally ruined our tr...
4      2022  Airline Rating  horse airline ever onâât recommend anyone to t...
...     ...             ...                                                ...
23294  2018      Trustpilot  it was fine the flight attendants were nice an...
23295  2018      Trustpilot  first time flying with american airline on bus...
23296  2018      Trustpilot  there were too many instances of rude service ...
23297  2018      Trustpilot  have a business class ticket and had access to...
23298  2018      Trustpilot  terrible experience by daughters flight from r...

[23299 rows x 3 columns]

In [ ]:
# Non-ACII removal
def replace_ascii(text):
  pattern = r'[^\x00-\x7F]+'
  text = re.sub(pattern,"",text)
  return text

In [ ]:
# apply the remove_markers function to the 'my_column' column
df['Review'] = df['Review'].apply(replace_ascii)
df

       Year     Data_Source                                             Review
0      2022  Airline Rating  i tried to fly out of gjt yesterday afternoon ...
1      2022  Airline Rating  the rude woman at the front desk got mad at me...
2      2022  Airline Rating  since were back to our normal  miles or so a y...
3      2022  Airline Rating  you k american airline literally ruined our tr...
4      2022  Airline Rating  horse airline ever ont recommend anyone to tra...
...     ...             ...                                                ...
23294  2018      Trustpilot  it was fine the flight attendants were nice an...
23295  2018      Trustpilot  first time flying with american airline on bus...
23296  2018      Trustpilot  there were too many instances of rude service ...
23297  2018      Trustpilot  have a business class ticket and had access to...
23298  2018      Trustpilot  terrible experience by daughters flight from r...

[23299 rows x 3 columns]

# **Tokenisation and Lemmatization with SpaCy**

In [ ]:
import pandas as pd
import spacy

# Load the English language model
nlp = spacy.load('en_core_web_sm')

# Function to lemmatize a sentence, convert past tense verbs to present tense, convert plural nouns to singular nouns,
# and convert adjectives and adverbs to their base forms
def lemmatize_and_convert(text):
    doc = nlp(text)
    converted_tokens = []
    for token in doc:
        # Lemmatize verbs, nouns, adjectives, and adverbs
        if token.pos_ in ('VERB', 'NOUN', 'ADJ', 'ADV'):
            converted_tokens.append(token.lemma_)
        else:
            converted_tokens.append(token.text)
    return ' '.join(converted_tokens)

if __name__ == "__main__":
    # Assuming you have loaded the DataFrame 'df' with a 'Review' column containing the sentences.

    # Apply the lemmatize_and_convert function to the 'Review' column
    df['Review'] = df['Review'].apply(lambda x: lemmatize_and_convert(str(x)))

In [ ]:
df

       Year     Data_Source                                             Review
0      2022  Airline Rating  try fly gjt yesterday afternoon fly decade iss...
1      2022  Airline Rating  rude woman desk mad ask check luggage early kn...
2      2022  Airline Rating  normal mile year think ofd remount experience ...
3      2022  Airline Rating  american airline literally ruin trip good angr...
4      2022  Airline Rating  horse airline ont recommend travel american ai...
...     ...             ...                                                ...
23294  2018      Trustpilot  fine flight attendant nice seat pretty comfort...
23295  2018      Trustpilot  time fly american airline business experience ...
23296  2018      Trustpilot  instance rude service ignore ofll describe ins...
23297  2018      Trustpilot  business class ticket access complimentary pre...
23298  2018      Trustpilot  terrible experience daughter flight rdu jfk ca...

[23299 rows x 3 columns]

# **Stop words removal with spacy**

In [ ]:
import spacy
import pandas as pd

# Load spacy model
nlp = spacy.load('en_core_web_sm')

# Function to remove stopwords from a sentence
def process_text(text):
    doc = nlp(text)
    filtered_words = [token.text for token in doc if not token.is_stop]
    return ' '.join(filtered_words)

if __name__ == "__main__":
    # Create or read the DataFrame 'df' with the 'Review' column
    # Example: df = pd.DataFrame({'Review': ['I went to the stores', 'He visited the parks', 'They ate pizzas', 'It is very beautiful and wonderfully done.']})

    # Apply the process_text function to the 'Review' column
    df['Review'] = df['Review'].apply(lambda x: process_text(str(x)))

    print(df)

       Year     Data_Source                                             Review
0      2022  Airline Rating  try fly gjt yesterday afternoon fly decade iss...
1      2022  Airline Rating  rude woman desk mad ask check luggage early kn...
2      2022  Airline Rating  normal mile year think ofd remount experience ...
3      2022  Airline Rating  american airline literally ruin trip good angr...
4      2022  Airline Rating  horse airline ont recommend travel american ai...
...     ...             ...                                                ...
23294  2018      Trustpilot  fine flight attendant nice seat pretty comfort...
23295  2018      Trustpilot  time fly american airline business experience ...
23296  2018      Trustpilot  instance rude service ignore ofll describe ins...
23297  2018      Trustpilot  business class ticket access complimentary pre...
23298  2018      Trustpilot  terrible experience daughter flight rdu jfk ca...

[23299 rows x 3 columns]

In [ ]:
df

       Year     Data_Source                                             Review
0      2022  Airline Rating  try fly gjt yesterday afternoon fly decade iss...
1      2022  Airline Rating  rude woman desk mad ask check luggage early kn...
2      2022  Airline Rating  normal mile year think ofd remount experience ...
3      2022  Airline Rating  american airline literally ruin trip good angr...
4      2022  Airline Rating  horse airline ont recommend travel american ai...
...     ...             ...                                                ...
23294  2018      Trustpilot  fine flight attendant nice seat pretty comfort...
23295  2018      Trustpilot  time fly american airline business experience ...
23296  2018      Trustpilot  instance rude service ignore ofll describe ins...
23297  2018      Trustpilot  business class ticket access complimentary pre...
23298  2018      Trustpilot  terrible experience daughter flight rdu jfk ca...

[23299 rows x 3 columns]

In [ ]:
# exclude the word not
import spacy
import pandas as pd

# Load spacy model
nlp = spacy.load('en_core_web_sm')

# Function to remove stopwords and the word "not" from a sentence
def process_text(text):
    doc = nlp(text)
    filtered_words = [token.text for token in doc if not token.is_stop and token.text.lower() != 'not']
    return ' '.join(filtered_words)

if __name__ == "__main__":
    # Create or read the DataFrame 'df' with the 'Review' column
    # Example: df = pd.DataFrame({'Review': ['I went to the stores', 'He visited the parks', 'They ate pizzas', 'It is very beautiful and wonderfully done.']})

    # Apply the process_text function to the 'Review' column
    df['Review'] = df['Review'].apply(lambda x: process_text(str(x)))

(df)

       Year     Data_Source                                             Review
0      2022  Airline Rating  try fly gjt yesterday afternoon fly decade iss...
1      2022  Airline Rating  rude woman desk mad ask check luggage early kn...
2      2022  Airline Rating  normal mile year think ofd remount experience ...
3      2022  Airline Rating  american airline literally ruin trip good angr...
4      2022  Airline Rating  horse airline ont recommend travel american ai...
...     ...             ...                                                ...
23294  2018      Trustpilot  fine flight attendant nice seat pretty comfort...
23295  2018      Trustpilot  time fly american airline business experience ...
23296  2018      Trustpilot  instance rude service ignore ofll describe ins...
23297  2018      Trustpilot  business class ticket access complimentary pre...
23298  2018      Trustpilot  terrible experience daughter flight rdu jfk ca...

[23299 rows x 3 columns]

# **Removing unwanted **

In [ ]:
# remove empty rows after preprocessing
df.dropna(subset=['Review'], inplace=True)
df = df[~(df['Review'] == '[]')]

In [ ]:
df['Review'] = df['Review'].str.strip('[]')

In [ ]:
df

       Year     Data_Source                                             Review
0      2022  Airline Rating  try fly gjt yesterday afternoon fly decade iss...
1      2022  Airline Rating  rude woman desk mad ask check luggage early kn...
2      2022  Airline Rating  normal mile year think ofd remount experience ...
3      2022  Airline Rating  american airline literally ruin trip good angr...
4      2022  Airline Rating  horse airline ont recommend travel american ai...
...     ...             ...                                                ...
23294  2018      Trustpilot  fine flight attendant nice seat pretty comfort...
23295  2018      Trustpilot  time fly american airline business experience ...
23296  2018      Trustpilot  instance rude service ignore ofll describe ins...
23297  2018      Trustpilot  business class ticket access complimentary pre...
23298  2018      Trustpilot  terrible experience daughter flight rdu jfk ca...

[23299 rows x 3 columns]

In [ ]:
# remove anyword with less than 3 characters
def remove_short_words(text):
    if text is None:
        return ''
    words = text.split()
    words = [word for word in words if len(word) > 2]
    return ' '.join(words)

In [ ]:
df['Review'] = df['Review'].apply(remove_short_words)

In [ ]:
df

       Year     Data_Source                                             Review
0      2022  Airline Rating  try fly gjt yesterday afternoon fly decade iss...
1      2022  Airline Rating  rude woman desk mad ask check luggage early kn...
2      2022  Airline Rating  normal mile year think ofd remount experience ...
3      2022  Airline Rating  american airline literally ruin trip good angr...
4      2022  Airline Rating  horse airline ont recommend travel american ai...
...     ...             ...                                                ...
23294  2018      Trustpilot  fine flight attendant nice seat pretty comfort...
23295  2018      Trustpilot  time fly american airline business experience ...
23296  2018      Trustpilot  instance rude service ignore ofll describe ins...
23297  2018      Trustpilot  business class ticket access complimentary pre...
23298  2018      Trustpilot  terrible experience daughter flight rdu jfk ca...

[23299 rows x 3 columns]

## **Saving the file**

In [ ]:
df.to_csv('all_review_clean(2018-2022).csv', index=False)